SET SERVEROUTPUT ON;

DECLARE
    v_table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'STADIUMS';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE stadiums CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE stadiums (
                stadium_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                stadium_name       VARCHAR2(120) NOT NULL,
                stadium_location   VARCHAR2(200) NOT NULL,
                associated_club    VARCHAR2(120) NOT NULL
            )
        ]';
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE stadiums (
                stadium_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                stadium_name       VARCHAR2(120) NOT NULL,
                stadium_location   VARCHAR2(200) NOT NULL,
                associated_club    VARCHAR2(120) NOT NULL
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'CLUBS';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE clubs CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE clubs (
                club_id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                team_name                VARCHAR2(120) NOT NULL UNIQUE,
                team_logo                VARCHAR(200),
                club_manager_id          NUMBER,
                club_manager_photo       VARCHAR(200),
                ass_club_manager        VARCHAR2(160),
                ass_club_manager_photo  VARCHAR2(200),
                club_location_id         NUMBER,
                club_history             CLOB,
                CONSTRAINT fk_clubs_stadium FOREIGN KEY (club_location_id) REFERENCES stadiums(stadium_id)
            )
        ]';
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE clubs (
                club_id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                team_name                VARCHAR2(120) NOT NULL UNIQUE,
                team_logo                VARCHAR(200),
                club_manager_id          NUMBER,
                club_manager_photo       VARCHAR(200),
                ass_club_manager        VARCHAR2(160),
                ass_club_manager_photo  VARCHAR2(200),
                club_location_id         NUMBER,
                club_history             CLOB,
                CONSTRAINT fk_clubs_stadium FOREIGN KEY (club_location_id) REFERENCES stadiums(stadium_id)
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'TEAM_MANAGERS';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE team_managers CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE team_managers (
                manager_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                first_name         VARCHAR2(80) NOT NULL,
                middle_name        VARCHAR2(80),
                last_name          VARCHAR2(80) NOT NULL,
                manager_photo      VARCHAR(200),
                manager_type       VARCHAR2(40) NOT NULL,
                team_id            NUMBER NOT NULL,
                manager_history    CLOB,
                CONSTRAINT ck_manager_type CHECK (manager_type IN ('Head Coach', 'Assistant Coach', 'General Manager')),
                CONSTRAINT fk_managers_team FOREIGN KEY (team_id) REFERENCES clubs(club_id)
            )
        ]';
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE team_managers (
                manager_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                first_name         VARCHAR2(80) NOT NULL,
                middle_name        VARCHAR2(80),
                last_name          VARCHAR2(80) NOT NULL,
                manager_photo      VARCHAR(200),
                manager_type       VARCHAR2(40) NOT NULL,
                team_id            NUMBER NOT NULL,
                manager_history    CLOB,
                CONSTRAINT ck_manager_type CHECK (manager_type IN ('Head Coach', 'Assistant Coach', 'General Manager')),
                CONSTRAINT fk_managers_team FOREIGN KEY (team_id) REFERENCES clubs(club_id)
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'PLAYERS';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE players CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE players (
                player_id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                first_name               VARCHAR2(80) NOT NULL,
                middle_name              VARCHAR2(80),
                last_name                VARCHAR2(80) NOT NULL,
                player_photo             VARCHAR(200),
                date_of_birth            DATE NOT NULL,
                age                      NUMBER(3) NOT NULL,
                team_id                  NUMBER NOT NULL,
                player_history           CLOB,
                jersey_number            NUMBER(3) NOT NULL,
                position_code            VARCHAR2(20) NOT NULL,
                current_season_stats     CLOB,
                career_stats             CLOB,
                CONSTRAINT ck_player_position CHECK (position_code IN ('PG', 'SG', 'SF', 'PF', 'C')),
                CONSTRAINT fk_players_team FOREIGN KEY (team_id) REFERENCES clubs(club_id)
            )
        ]';
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE players (
                player_id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                first_name               VARCHAR2(80) NOT NULL,
                middle_name              VARCHAR2(80),
                last_name                VARCHAR2(80) NOT NULL,
                player_photo             VARCHAR(200),
                date_of_birth            DATE NOT NULL,
                age                      NUMBER(3) NOT NULL,
                team_id                  NUMBER NOT NULL,
                player_history           CLOB,
                jersey_number            NUMBER(3) NOT NULL,
                position_code            VARCHAR2(20) NOT NULL,
                current_season_stats     CLOB,
                career_stats             CLOB,
                CONSTRAINT ck_player_position CHECK (position_code IN ('PG', 'SG', 'SF', 'PF', 'C')),
                CONSTRAINT fk_players_team FOREIGN KEY (team_id) REFERENCES clubs(club_id)
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'USERS';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE users (
                user_id       VARCHAR2(8) PRIMARY KEY,
                first_name    VARCHAR2(15) NOT NULL,
                last_name     VARCHAR2(15) NOT NULL,
                email_address VARCHAR2(15) NOT NULL,
                password      CLOB NOT NULL,
                fav_team_id   NUMBER,
                CONSTRAINT fk_users_fav_team FOREIGN KEY (fav_team_id) REFERENCES clubs(club_id)
            )
        ]';
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE users (
                user_id       VARCHAR2(8) PRIMARY KEY,
                first_name    VARCHAR2(15) NOT NULL,
                last_name     VARCHAR2(15) NOT NULL,
                email_address VARCHAR2(15) NOT NULL,
                password      CLOB NOT NULL,
                fav_team_id   NUMBER,
                CONSTRAINT fk_users_fav_team FOREIGN KEY (fav_team_id) REFERENCES clubs(club_id)
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'ADMIN_USERS';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE admin_users CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE admin_users (
                admin_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                username      VARCHAR2(80) NOT NULL UNIQUE,
                password_hash CLOB NOT NULL,
                created_at    DATE DEFAULT SYSDATE NOT NULL
            )
        ]';
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE admin_users (
                admin_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                username      VARCHAR2(80) NOT NULL UNIQUE,
                password_hash CLOB NOT NULL,
                created_at    DATE DEFAULT SYSDATE NOT NULL
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'INJURIES';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE injuries CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE injuries (
                injury_id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                injury_name                  VARCHAR2(120) NOT NULL,
                injury_type                  VARCHAR2(120) NOT NULL,
                injury_description           CLOB,
                injury_resources             VARCHAR2(500),
                injury_video_description     VARCHAR2(500)
            )
        ]';
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE injuries (
                injury_id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                injury_name                  VARCHAR2(120) NOT NULL,
                injury_type                  VARCHAR2(120) NOT NULL,
                injury_description           CLOB,
                injury_resources             VARCHAR2(500),
                injury_video_description     VARCHAR2(500)
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'INJURED_PLAYERS';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE injured_players CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE injured_players (
                injured_player_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                player_id                    NUMBER NOT NULL,
                injury_id                    NUMBER NOT NULL,
                injury_name                  VARCHAR2(120) NOT NULL,
                expected_time_of_return      DATE,
                injury_start_date            DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                injury_status                VARCHAR2(20) DEFAULT 'CURRENT' NOT NULL,
                CONSTRAINT ck_injury_status CHECK (injury_status IN ('CURRENT', 'RECOVERED')),
                CONSTRAINT fk_injured_player_player FOREIGN KEY (player_id) REFERENCES players(player_id),
                CONSTRAINT fk_injured_player_injury FOREIGN KEY (injury_id) REFERENCES injuries(injury_id)
            )
        ]';
        
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE injured_players (
                injured_player_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                player_id                    NUMBER NOT NULL,
                injury_id                    NUMBER NOT NULL,
                injury_name                  VARCHAR2(120) NOT NULL,
                expected_time_of_return      DATE,
                injury_start_date            DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                injury_status                VARCHAR2(20) DEFAULT 'CURRENT' NOT NULL,
                CONSTRAINT ck_injury_status CHECK (injury_status IN ('CURRENT', 'RECOVERED')),
                CONSTRAINT fk_injured_player_player FOREIGN KEY (player_id) REFERENCES players(player_id),
                CONSTRAINT fk_injured_player_injury FOREIGN KEY (injury_id) REFERENCES injuries(injury_id)
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'FIXTURES';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE fixtures CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE fixtures (
                fixture_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                fixture_date           DATE NOT NULL,
                fixture_time           DATE NOT NULL,
                home_team_id           NUMBER NOT NULL,
                home_team_logo         VARCHAR(200),
                away_team_id           NUMBER NOT NULL,
                away_team_logo         VARCHAR(200),
                fixture_location       VARCHAR2(200) NOT NULL,
                fixture_status         VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
                home_score             NUMBER(3),
                away_score             NUMBER(3),
                CONSTRAINT ck_fixture_status CHECK (fixture_status IN ('SCHEDULED', 'LIVE', 'COMPLETED')),
                CONSTRAINT ck_fixture_teams CHECK (home_team_id <> away_team_id),
                CONSTRAINT fk_fixtures_home_team FOREIGN KEY (home_team_id) REFERENCES clubs(club_id),
                CONSTRAINT fk_fixtures_away_team FOREIGN KEY (away_team_id) REFERENCES clubs(club_id)
            )
        ]';
        
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE fixtures (
                fixture_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                fixture_date           DATE NOT NULL,
                fixture_time           DATE NOT NULL,
                home_team_id           NUMBER NOT NULL,
                home_team_logo         VARCHAR(100),
                away_team_id           NUMBER NOT NULL,
                away_team_logo         VARCHAR(100),
                fixture_location       VARCHAR2(200) NOT NULL,
                fixture_status         VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
                home_score             NUMBER(3),
                away_score             NUMBER(3),
                CONSTRAINT ck_fixture_status CHECK (fixture_status IN ('SCHEDULED', 'LIVE', 'COMPLETED')),
                CONSTRAINT ck_fixture_teams CHECK (home_team_id <> away_team_id),
                CONSTRAINT fk_fixtures_home_team FOREIGN KEY (home_team_id) REFERENCES clubs(club_id),
                CONSTRAINT fk_fixtures_away_team FOREIGN KEY (away_team_id) REFERENCES clubs(club_id)
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'TEAM_STATISTICS';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE team_statistics CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE team_statistics (
                team_stat_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                team_id                NUMBER NOT NULL,
                season_label           VARCHAR2(20) NOT NULL,
                games_played           NUMBER DEFAULT 0 NOT NULL,
                wins                   NUMBER DEFAULT 0 NOT NULL,
                losses                 NUMBER DEFAULT 0 NOT NULL,
                league_points          NUMBER DEFAULT 0 NOT NULL,
                points_scored          NUMBER DEFAULT 0 NOT NULL,
                points_allowed         NUMBER DEFAULT 0 NOT NULL,
                offensive_rating       NUMBER(8,2) DEFAULT 0 NOT NULL,
                defensive_rating       NUMBER(8,2) DEFAULT 0 NOT NULL,
                net_rating             NUMBER(8,2) DEFAULT 0 NOT NULL,
                CONSTRAINT uq_team_statistics UNIQUE (team_id, season_label),
                CONSTRAINT fk_team_statistics_team FOREIGN KEY (team_id) REFERENCES clubs(club_id)
            )
        ]';
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE team_statistics (
                team_stat_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                team_id                NUMBER NOT NULL,
                season_label           VARCHAR2(20) NOT NULL,
                games_played           NUMBER DEFAULT 0 NOT NULL,
                wins                   NUMBER DEFAULT 0 NOT NULL,
                losses                 NUMBER DEFAULT 0 NOT NULL,
                league_points          NUMBER DEFAULT 0 NOT NULL,
                points_scored          NUMBER DEFAULT 0 NOT NULL,
                points_allowed         NUMBER DEFAULT 0 NOT NULL,
                offensive_rating       NUMBER(8,2) DEFAULT 0 NOT NULL,
                defensive_rating       NUMBER(8,2) DEFAULT 0 NOT NULL,
                net_rating             NUMBER(8,2) DEFAULT 0 NOT NULL,
                CONSTRAINT uq_team_statistics UNIQUE (team_id, season_label),
                CONSTRAINT fk_team_statistics_team FOREIGN KEY (team_id) REFERENCES clubs(club_id)
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'PLAYER_STATISTICS';
    IF v_table_count = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE player_statistics CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE q'[
            CREATE TABLE player_statistics (
                player_stat_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                player_id              NUMBER NOT NULL,
                season_label           VARCHAR2(20) NOT NULL,
                games_played           NUMBER DEFAULT 0 NOT NULL,
                points_per_game        NUMBER(6,2) DEFAULT 0 NOT NULL,
                assists_per_game       NUMBER(6,2) DEFAULT 0 NOT NULL,
                rebounds_per_game      NUMBER(6,2) DEFAULT 0 NOT NULL,
                steals_per_game        NUMBER(6,2) DEFAULT 0 NOT NULL,
                blocks_per_game        NUMBER(6,2) DEFAULT 0 NOT NULL,
                CONSTRAINT uq_player_statistics UNIQUE (player_id, season_label),
                CONSTRAINT fk_player_statistics_player FOREIGN KEY (player_id) REFERENCES players(player_id)
            )
        ]';
        
    ELSE
        EXECUTE IMMEDIATE q'[
            CREATE TABLE player_statistics (
                player_stat_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                player_id              NUMBER NOT NULL,
                season_label           VARCHAR2(20) NOT NULL,
                games_played           NUMBER DEFAULT 0 NOT NULL,
                points_per_game        NUMBER(6,2) DEFAULT 0 NOT NULL,
                assists_per_game       NUMBER(6,2) DEFAULT 0 NOT NULL,
                rebounds_per_game      NUMBER(6,2) DEFAULT 0 NOT NULL,
                steals_per_game        NUMBER(6,2) DEFAULT 0 NOT NULL,
                blocks_per_game        NUMBER(6,2) DEFAULT 0 NOT NULL,
                CONSTRAINT uq_player_statistics UNIQUE (player_id, season_label),
                CONSTRAINT fk_player_statistics_player FOREIGN KEY (player_id) REFERENCES players(player_id)
            )
        ]';
    END IF;
END;
/

CREATE INDEX idx_players_team_id ON players(team_id);
CREATE INDEX idx_managers_team_id ON team_managers(team_id);
CREATE INDEX idx_fixtures_date_status ON fixtures(fixture_date, fixture_status);
CREATE INDEX idx_injured_players_status ON injured_players(injury_status);

