name: Deploy and Remote Sync

on:
  push:
    branches:
      - prod
  
env:
  # Expose repo variables/secrets to steps as needed
  ORACLE_DRIVER: ${{ vars.ORACLE_DRIVER }}
  ORACLE_CONNECTION_STRING: ${{ secrets.ORACLE_CONNECTION_STRING }}
  ORACLE_CONFIG_DIR: ${{ secrets.ORACLE_CONFIG_DIR }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USERNAME }}
  PRIVATE_KEY: ${{ secrets.SSH_KEY }}
  REPO_PATH: /home/${{ secrets.SERVER_USERNAME }}/Basketball-League-Management-System
  DB_CONFIG_FILE: ${{ secrets.DB_CONFIG_FILE }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Successful connection to the server
        run: |
            echo "$PRIVATE_KEY" > private-key && chmod 700 private-key
            ssh -o StrictHostKeyChecking=no -i private-key ${SERVER_USER}@${SERVER_IP} '
              # Identify user and IPs
              whoami
              echo "Connected to server at $(hostname -I)"
            '
            rm -f private-key

      - name: Check NGINX and Go in server and start NGINX
        run: |
          echo "$PRIVATE_KEY" > private-key && chmod 600 private-key
          ssh -o StrictHostKeyChecking=no -i private-key ${SERVER_USER}@${SERVER_IP} '
            sudo dnf update -y
            sudo dnf install -y nginx golang


            if command -v go >/dev/null 2>&1; then
              echo "Go is installed: $(go version)"
            fi
            sudo systemctl enable nginx
            sudo systemctl start nginx
            '
          rm -f private-key

    
  deploy:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Update application repo and run server
        run: |
          echo "$PRIVATE_KEY" > private-key && chmod 700 private-key
          ssh -o StrictHostKeyChecking=no -i private-key ${SERVER_USER}@${SERVER_IP} '
              if [ -d "${REPO_PATH}" ]; then
                kill -9 blms
                cd ${REPO_PATH}
                git fetch origin prod
              else
                echo "Directory ${REPO_PATH} does not exist. Proceeding to clone the repository."
                git clone -b prod https://github.com/Muturi-002/Basketball-League-Management-System.git
                cd ${REPO_PATH}
                rm -rf .github/
                cat ${DB_CONFIG_FILE} > .env
              fi
              cd '${REPO_PATH}/Backend'
              go build -o blms .
              go run . > backend.log 2>&1 &
            '
            rm -f private-key

      - name: Check if the server is running
        run: |
          echo "$PRIVATE_KEY" > private-key && chmod 700 private-key
          ssh -o StrictHostKeyChecking=no -i private-key ${SERVER_USER}@${SERVER_IP} '
            if pgrep -f "./blms" >/dev/null; then
              echo "Server is running."
            else
              echo "Server is not running."
              exit 1
            fi
          '
          rm -f private-key
      
      - name: Configure NGINX
        run: |
          echo "$PRIVATE_KEY" > private-key && chmod 700 private-key
          ssh -o StrictHostKeyChecking=no -i private-key ${SERVER_USER}@${SERVER_IP} '
            sudo tee /etc/nginx/conf.d/goapp.conf > /dev/null <<EOF
            server {
              server {
                listen 80;
                server_name _; 

                # Public server on port 4000
                location / {
                    proxy_pass http://127.0.0.1:4000;
                    proxy_http_version 1.1;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }

                # Admin/Private server on port 4900
                location /admin {
                    proxy_pass http://127.0.0.1:4900;
                    proxy_http_version 1.1;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }

          '
          sudo nginx -t
          sudo systemctl restart nginx
          rm -f private-key

        
